const equipos = [
  { nombre: "Boston Celtics", abreviado: "BOS", logo: "img/bos.svg" },
  { nombre: "Brooklyn Nets", abreviado: "BKN", logo: "img/bkn.svg" },
  { nombre: "New York Knicks", abreviado: "NYK", logo: "img/nyk.svg" },
  { nombre: "Philadelphia 76ers", abreviado: "PHI", logo: "img/phi.svg" },
  { nombre: "Toronto Raptors", abreviado: "TOR", logo: "img/tor.svg" },
  { nombre: "Chicago Bulls", abreviado: "CHI", logo: "img/chi.svg" },
  { nombre: "Cleveland Cavaliers", abreviado: "CLE", logo: "img/cle.svg" },
  { nombre: "Detroit Pistons", abreviado: "DET", logo: "img/det.svg" },
  { nombre: "Indiana Pacers", abreviado: "IND", logo: "img/ind.svg" },
  { nombre: "Milwaukee Bucks", abreviado: "MIL", logo: "img/mil.svg" },
  { nombre: "Atlanta Hawks", abreviado: "ATL", logo: "img/atl.svg" },
  { nombre: "Charlotte Hornets", abreviado: "CHA", logo: "img/cha.svg" },
  { nombre: "Miami Heat", abreviado: "MIA", logo: "img/mia.svg" },
  { nombre: "Orlando Magic", abreviado: "ORL", logo: "img/orl.svg" },
  { nombre: "Washington Wizards", abreviado: "WAS", logo: "img/was.svg" },
  { nombre: "Denver Nuggets", abreviado: "DEN", logo: "img/den.svg" },
  { nombre: "Minnesota Timberwolves", abreviado: "MIN", logo: "img/min.svg" },
  { nombre: "Oklahoma City Thunder", abreviado: "OKC", logo: "img/okc.svg" },
  { nombre: "Portland Trail Blazers", abreviado: "POR", logo: "img/por.svg" },
  { nombre: "Utah Jazz", abreviado: "UTA", logo: "img/uta.svg" },
  { nombre: "Golden State Warriors", abreviado: "GSW", logo: "img/gsw.svg" },
  { nombre: "LA Clippers", abreviado: "LAC", logo: "img/lac.svg" },
  { nombre: "Los Angeles Lakers", abreviado: "LAL", logo: "img/lal.svg" },
  { nombre: "Phoenix Suns", abreviado: "PHX", logo: "img/phx.svg" },
  { nombre: "Sacramento Kings", abreviado: "SAC", logo: "img/sac.svg" },
  { nombre: "Dallas Mavericks", abreviado: "DAL", logo: "img/dal.svg" },
  { nombre: "Houston Rockets", abreviado: "HOU", logo: "img/hou.svg" },
  { nombre: "Memphis Grizzlies", abreviado: "MEM", logo: "img/mem.svg" },
  { nombre: "New Orleans Pelicans", abreviado: "NOP", logo: "img/nop.svg" },
  { nombre: "San Antonio Spurs", abreviado: "SAS", logo: "img/sas.svg" },
];
